const express = require('express')
const router = express.Router()

let client = null
try {
  if (process.env.ANTHROPIC_API_KEY) {
    const Anthropic = require('@anthropic-ai/sdk')
    client = new Anthropic()
  }
} catch (e) {
  console.warn('Anthropic SDK not available, LLM tie-break disabled')
}

router.post('/', async (req, res) => {
  if (!client) return res.json({ verdict: 'AMBIGUOUS', reasoning: 'LLM not configured' })

  const { edits, finalText } = req.body
  try {
    const msg = await client.messages.create({
      model: 'claude-opus-4-6',
      max_tokens: 200,
      messages: [{
        role: 'user',
        content: `You are analyzing whether a piece of writing was composed by a human or transcribed/generated by AI.

Edit profile: ${JSON.stringify(edits)}
Final text excerpt: ${finalText}

Based on the edit pattern, does this look like genuine compositional thinking (human writing with organic revisions) or mechanical transcription/AI generation?

Respond with exactly: COMPOSITION, TRANSCRIPTION, or AMBIGUOUS
Then on the next line, one sentence of reasoning.`
      }]
    })
    const lines = msg.content[0].text.trim().split('\n')
    const verdict = ['COMPOSITION', 'TRANSCRIPTION', 'AMBIGUOUS'].includes(lines[0]) ? lines[0] : 'AMBIGUOUS'
    res.json({ verdict, reasoning: lines[1] || '' })
  } catch (e) {
    res.json({ verdict: 'AMBIGUOUS', reasoning: 'LLM error: ' + e.message })
  }
})

module.exports = router
